# Site settings
title: 咀嚼之味
owner: 邹润阳
email: jerry.zry@outlook.com
description: 咀嚼之味是我分享我对编程与生活的见解之地。我喜欢做一些安静的事，比如看书、看电影、听音乐、散步以及旅行。
baseurl: ""
url: "https://jerryzou.com"

#static images
local_url: "/assets/images"
#github source
static_url: "/assets/images"
#digitalocean cdn
#static_url: "https://sinacloud.net/heaven-blog-files/images"

# Build settings
markdown: kramdown
permalink: pretty
paginate: 7
paginate_path: ":num/"
exclude: [node_modules, .tmp, Gruntfile.js, _config, package.json, articles.raw, vendor]

# default Front matter
defaults:
  -
    scope:
      path: pages
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      copyright: true
      disqus_comment: false
      release: true
