# Site settings
title: 咀嚼之味
owner: 邹润阳
email: jerry.zry@outlook.com
description: >
  咀嚼之味是我分享我对编程与生活的见解之地。在我看来，编程不仅仅是我与生俱来的使命，也是我快乐的源泉。在业余时间，我喜欢研究一些跟技术相关的东西。同时，我也喜欢做一些安静的事，比如看书、看电影、听音乐、一个人散步以及旅行。
baseurl: ""
url: "https://jerryzou.com"

#static images
local_url: "/assets/images"
#github source
#static_url: "/assets/images"
#upyun source
#static_url: "https://jerryblog-image.b0.upaiyun.com/blog"
#digitalocean cdn
static_url: "https://jerryz.sgp1.cdn.digitaloceanspaces.com/resources/blog"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 7
paginate_path: ":num/"
exclude: [node_modules, .tmp, Gruntfile.js, _config, package.json, articles.raw, vendor]

# default Front matter
defaults:
  -
    scope:
      path: pages
      type: pages
    values:
      layout: page
  -
    scope:
      path: ""
      type: posts
    values:
      layout: post
      copyright: true
      disqus_comment: true
      release: true
